### ISSUE TITLE
AP on weapon

### ISSUE THREAD

**Issue by bishem** [Dave-Hughes/MerchantGameDB#25]
the AP on Leavateinn is neither displayed after craft on it nor does it show on menu after wearing it
i spend a lot time on making it so it kinda sucks

**Comment by Benzeliden** [comment]
Well, it's game issue, not db issue
You can try to send bugreport from game. I sent it some times ago but nothing was fixed

And about db - probably we can only mark bugged stats to notify users that those attributes not working properly
